// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_menu

#ifndef _SQUARELINE_MENU_UI_H
#define _SQUARELINE_MENU_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_760006719);   // assets\信号3.png
LV_IMG_DECLARE( ui_img_1187237374);   // assets\卡1.png
LV_IMG_DECLARE( ui_img_26967346);   // assets\电池5.png
LV_IMG_DECLARE( ui_img_1088127317);   // assets\声音.png
LV_IMG_DECLARE( ui_img_a_png);   // assets\A.png
LV_IMG_DECLARE( ui_img_slec_png);   // assets\slec.png
LV_IMG_DECLARE( ui_img_1_png);   // assets\1.png
LV_IMG_DECLARE( ui_img_2_png);   // assets\2.png
LV_IMG_DECLARE( ui_img_3_png);   // assets\3.png
LV_IMG_DECLARE( ui_img_6_png);   // assets\6.png
LV_IMG_DECLARE( ui_img_7_png);   // assets\7.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
