// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_menu

#include "../ui.h"

void ui_comp_Switch1_create_hook( lv_obj_t * comp)
{
}
