// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_menu

#include "../ui.h"


// COMPONENT Switch1

lv_obj_t *ui_Switch1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Switch1;
cui_Switch1 = lv_switch_create(comp_parent);
lv_obj_set_width( cui_Switch1, 187);
lv_obj_set_height( cui_Switch1, 87);
lv_obj_set_x( cui_Switch1, 136 );
lv_obj_set_y( cui_Switch1, -125 );
lv_obj_set_align( cui_Switch1, LV_ALIGN_CENTER );

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCH1_NUM);
children[UI_COMP_SWITCH1_SWITCH1] = cui_Switch1;
lv_obj_add_event_cb(cui_Switch1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Switch1, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Switch1_create_hook(cui_Switch1);
return cui_Switch1; 
}

