// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Alarm_Project

#ifndef _ALARM_PROJECT_UI_H
#define _ALARM_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Image1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1181773158);   // assets\001-什么都没-添加闹钟.png
LV_IMG_DECLARE( ui_img_335732264);   // assets\002闹钟.png
LV_IMG_DECLARE( ui_img_827073802);   // assets\组 24.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
